---
sidebar: sidebar 
permalink: docs/hcc_inventory.html 
summary: Im Hybrid Cloud Control können Sie den Bestand Ihres Systems anzeigen. 
keywords: netapp, hci, hcc, on premise, inventory, hybrid cloud control 
---
= Anzeigen des NetApp HCI-Inventars in der Hybrid Cloud Control
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können den Bestand Ihres NetApp HCI Systems unter Hybrid Cloud Control anzeigen.



== Schritte

. Rufen Sie die https://fabric.netapp.io["NetApp Fabric Orchestrator"^] Anmeldeseite auf.
. Geben Sie Ihre Zugangsdaten für Cloud Central ein und wählen Sie *Login*.
+

TIP: Wenn keine der aufgeführten Systeme angezeigt werden, stellen Sie sicher, dass der NetApp HCI Administrator zu Ihrem NetApp Cloud Central Konto hinzugefügt wird.

. Wenn Sie kein Cloud Central-Konto haben, wählen Sie auf der Anmeldeseite von Cloud Central *Anmelden* aus.
+
Über Cloud Central können Sie Konten entweder als einzelne Konten oder als Federated-Konten einrichten:

+
.. Sie können ein neues Konto mit Namen, E-Mail und Passwort erstellen und dann werden Sie angemeldet. Dies ist die einfachste Art von Konto.
.. Wenn Sie Teil einer Cloud Central Federated Organisation sind, geben Sie Ihre E-Mail ein und werden dann zum Login des Unternehmens weitergeleitet.


. Wählen Sie aus anderen Cloud Central Produkten *Produkte* > *NetApp Fabric Orchestrator* aus.


[discrete]
== Weitere Informationen

* https://cloud.netapp.com/home["NetApp Cloud Central"^]
* https://docs.netapp.com/us-en/cloud/["NetApp Cloud-Dokumentation"^]

