---
sidebar: sidebar 
permalink: docs/task_mnode_api_find_mgmt_svcs_version.html 
summary: Die vom Management-Node verwendeten Versionen für das Betriebssystem und die Managementservices finden Sie mithilfe der REST-API. 
keywords: netapp, hci, management node, management services, version, bundle version, what is 
---
= Überprüfen Sie die Betriebssystem- und Servicestversionen der Management-Nodes
:allow-uri-read: 


[role="lead"]
Sie können die Versionsnummern des Management-Node-Betriebssystems, des Managementservices-Pakets und der einzelnen Services, die auf dem Management-Node ausgeführt werden, mithilfe der REST-API im Management-Node überprüfen.

.Was Sie benötigen
* Auf dem Cluster wird die NetApp Element Software 11.3 oder höher ausgeführt.
* Sie haben einen Management-Node mit Version 11.3 oder höher implementiert.


.Optionen
* <<API-Befehle>>
* <<SCHRITTE DER REST API-UI>>




== API-Befehle

* Hier erhalten Sie Versionsinformationen zum Management-Node OS, zum Management-Services-Bundle und zum Management-Node-API-Service (mNode-API), der auf dem Management-Node ausgeführt wird:
+
[listing]
----
curl -X GET "https://<ManagementNodeIP>/mnode/about" -H  "accept: application/json"
----
* Abrufen der Versionsinformationen zu den einzelnen auf dem Management-Node ausgeführten Services:
+
[listing]
----
curl -X GET "https://<ManagementNodeIP>/mnode/services?status=running" -H  "accept: */*" -H  "Authorization: Bearer ${TOKEN}"
----
+

NOTE: Sie können den vom API-Befehl verwendeten Träger finden `${TOKEN}`, wenn Sie link:task_mnode_api_get_authorizationtouse.html["Autorisieren"]. Der Träger `${TOKEN}` ist in der Lockenantwort.





== SCHRITTE DER REST API-UI

. Greifen Sie auf die REST-API-UI für den Service zu, indem Sie die Management-Node-IP-Adresse gefolgt von `/mnode/`:
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. Führen Sie einen der folgenden Schritte aus:
+
** Hier erhalten Sie Versionsinformationen zum Management-Node OS, zum Management-Services-Bundle und zum Management-Node-API-Service (mNode-API), der auf dem Management-Node ausgeführt wird:
+
... Wählen Sie *GET /about* aus.
... Wählen Sie *Probieren Sie es aus*.
... Wählen Sie *Ausführen*.
+
Die Management Services Bundle Version (`"mnode_bundle_version"`), Management Node OS Version ) (`"os_version"`und Management Node API Version (`"version"`) sind im Antworttext angegeben.



** Abrufen der Versionsinformationen zu den einzelnen auf dem Management-Node ausgeführten Services:
+
... Wählen Sie *GET /Services*.
... Wählen Sie *Probieren Sie es aus*.
... Wählen Sie den Status als *läuft* aus.
... Wählen Sie *Ausführen*.
+
Die Dienste, die auf dem Management-Knoten ausgeführt werden, werden im Response Body angezeigt.







[discrete]
== Weitere Informationen

* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["Seite „NetApp HCI Ressourcen“"^]

