---
sidebar: sidebar 
permalink: docs/task_mnode_enable_activeIQ.html 
summary: 'Der Management-Node (mNode) kann zur Aktivierung der NetApp Active IQ- und NetApp HCI-Telemetrie verwendet werden.' 
keywords: netapp, hci, api, enable, active iq, activeiq, hci monitoring 
---
= Active IQ- und NetApp HCI-Monitoring aktivieren
:allow-uri-read: 


[role="lead"]
Das Active IQ-Storage-Monitoring für das Computing-Monitoring von NetApp HCI und NetApp HCI lässt sich aktivieren, falls dies bei der Installation oder einem Upgrade nicht bereits geschehen war. Wenn Sie die Telemetrie mithilfe der NetApp HCI Deployment Engine deaktiviert haben, müssen Sie dieses Verfahren möglicherweise verwenden.

Der Active IQ Collector Service leitet Konfigurationsdaten und softwarebasierte Element Cluster-Performance-Kennzahlen an NetApp Active IQ weiter, um historische Berichte zu erstellen und Performance-Monitoring nahezu in Echtzeit zu ermöglichen. Der NetApp HCI Monitoring Service ermöglicht die Weiterleitung von Storage-Cluster-Fehlern an vCenter zur Alarmbenachrichtigung.

.Was Sie benötigen
* Im Storage Cluster wird die NetApp Element Software 11.3 oder höher ausgeführt.
* Sie haben einen Management-Node mit Version 11.3 oder höher implementiert.
* Sie haben Internetzugang. Der Active IQ Collector Service kann nicht von dunklen Seiten verwendet werden.


.Schritte
. Holen Sie sich die Basis-Asset-ID für die Installation:
+
.. Öffnen Sie die REST API-UI für den Bestandsdienst auf dem Managementknoten:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Wählen Sie *autorisieren* aus, und füllen Sie Folgendes aus:
+
... Geben Sie den Benutzernamen und das Passwort für den Cluster ein.
... Geben Sie die Client-ID als `mnode-client`ein.
... Wählen Sie *autorisieren*, um eine Sitzung zu starten.
... Schließen Sie das Fenster.


.. Wählen Sie in DER REST API UI *GET ​/Installations* aus.
.. Wählen Sie *Probieren Sie es aus*.
.. Wählen Sie *Ausführen*.
.. Kopieren Sie aus dem Antworttext von Code 200 die `id` für die Installation.
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: Die Installation verfügt über eine Basiskonfiguration, die während der Installation oder eines Upgrades erstellt wurde.



. Telemetrie aktivieren:
+
.. Greifen Sie auf die mnode Service API UI auf dem Management Node zu, indem Sie die Management Node IP-Adresse gefolgt von `/mnode`:
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. Wählen Sie *autorisieren* oder ein Schloss-Symbol aus, und füllen Sie Folgendes aus:
+
... Geben Sie den Benutzernamen und das Passwort für den Cluster ein.
... Geben Sie die Client-ID als `mnode-client`ein.
... Wählen Sie *autorisieren*, um eine Sitzung zu starten.
... Schließen Sie das Fenster.


.. Konfigurieren der BasisinAssets:
+
... Wählen Sie *PUT /Assets/{Asset_id}* aus.
... Wählen Sie *Probieren Sie es aus*.
... Geben Sie die folgende in die JSON-Nutzlast ein:
+
[listing]
----
{
"telemetry_active": true
"config": {}
}
----
... Geben Sie die Basis-ID des vorherigen Schritts in *Asset_ID* ein.
... Wählen Sie *Ausführen*.
+
Der Active IQ Service wird automatisch neu gestartet, sobald die Assets geändert werden. Das Ändern von Anlagen führt zu einer kurzen Verzögerung, bevor Einstellungen angewendet werden.





. Wenn dies noch nicht der Fall ist, fügen Sie dem Management-Node bekannte Assets, die als Management-Node bekannt sind, eine vCenter-Controller-Ressource für das NetApp HCI-Monitoring (nur NetApp HCI-Installationen) und Hybrid Cloud Control (für alle Installationen) hinzu:
+

NOTE: Für NetApp HCI Monitoring Services ist ein Controller-Asset erforderlich.

+
.. Wählen Sie *POST /Assets/{Asset_id}/Controllers* aus, um eine Unterressource des Controllers hinzuzufügen.
.. Wählen Sie *Probieren Sie es aus*.
.. Geben Sie im Feld *Asset_id* die ID der übergeordneten Basis ein, die Sie in die Zwischenablage kopiert haben.
.. Geben Sie die erforderlichen Nutzlastwerte mit AS `vCenter`- und vCenter-Anmeldedaten ein `type`.
+
[listing]
----
{
"username": "string",
"password": "string",
"ip": "string",
"type": "vCenter",
"host_name": "string",
"config": {}
}
----
+

NOTE: `ip` Ist die vCenter-IP-Adresse.

.. Wählen Sie *Ausführen*.




[discrete]
== Weitere Informationen

* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element Plug-in für vCenter Server"^]

