---
sidebar: sidebar 
permalink: docs/task_nde_configure_new_vsphere.html 
summary: Erfahren Sie, wie Sie VMware vSphere während der NetApp HCI Implementierung konfigurieren. 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= Konfigurieren einer neuen VMware vSphere Umgebung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können im Rahmen des NetApp HCI-Installationsprozesses eine neue vSphere Umgebung implementieren, indem Sie einige der Netzwerkinformationen bereitstellen, die vSphere verwenden sollte. Wenn Sie vSphere mit einer IP-Adresse konfigurieren, kann die Adresse nach der Installation nicht mehr geändert werden.

.Was Sie benötigen
Sie haben die Netzwerkinformationen für die geplante vSphere Umgebung erhalten.

.Schritte
. Wählen Sie *Configure a New vSphere Deployment*.
. Wählen Sie die Version von vSphere aus, die während der Bereitstellung installiert werden soll.
. Konfiguration der neuen vSphere Umgebung mit einer der folgenden Optionen:
+
|===
| Option | Schritte 


| Verwenden Sie einen Domain-Namen (empfohlen).  a| 
.. Wählen Sie *Configure using a Fully Qualified Domain Name* aus.
.. Geben Sie den vCenter Server-Domänennamen in das Feld *vCenter Server Fully Qualified Domain Name* ein.
.. Geben Sie die IP-Adresse des DNS-Servers in das Feld * DNS-Server-IP-Adresse* ein.
.. Wählen Sie *Weiter*.




| Verwenden Sie eine IP-Adresse.  a| 
.. Wählen Sie *Konfigurieren mit einer IP-Adresse*.
.. Wählen Sie *Weiter*.


|===


[discrete]
== Weitere Informationen

* link:firmware_driver_versions.html["Unterstützte Firmware- und ESXi-Treiberversionen für NetApp HCI und Firmware-Versionen für NetApp HCI Storage Nodes"]

