---
sidebar: sidebar 
permalink: docs/task_nde_join_existing_vsphere.html 
summary: Erfahren Sie, wie Sie VMware vSphere während der NetApp HCI Implementierung konfigurieren. 
keywords: netapp, hci, netapp deployment engine, deployment, vsphere 
---
= Schließen Sie sich einer vorhandenen VMware vSphere Implementierung an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Konfigurieren Sie NetApp HCI, um die Vorteile einer vorhandenen vSphere-Bereitstellung zu nutzen, indem Sie die Netzwerkinformationen und -Anmeldeinformationen des vCenter Servers bereitstellen.

.Was Sie benötigen
* Wenn Sie einer vorhandenen vSphere 6.7-Bereitstellung beitreten, stellen Sie sicher, dass vCenter Server Version 6.7 Update 1 ausführt.
* Wenn Sie einer vorhandenen vSphere 6.5-Implementierung beitreten, stellen Sie sicher, dass vCenter Server Version 6.5 Update 2 oder höher ausführt.
* Holen Sie sich die Netzwerkdetails und die Anmeldedaten des Administrators für Ihre vorhandene vSphere Implementierung.


.Über diese Aufgabe
Wenn Sie mehrere vCenter Server-Systeme verbinden, die über den vCenter Linked Mode verbunden sind, erkennt NetApp HCI nur eines der vCenter Server Systeme.


NOTE: Die Verwendung des NetApp Element-Plug-ins für vCenter Server zur Verwaltung von Clusterressourcen von anderen vCenter-Servern aus link:https://docs.netapp.com/us-en/vcp/vcp_concept_linkedmode.html["VCenter Linked Mode"^]ist auf lokale Storage-Cluster beschränkt.

.Schritte
. Wählen Sie *Join and Extend an einer vorhandenen vSphere-Bereitstellung* aus.
. Geben Sie den Domainnamen oder die IP-Adresse in das Feld *vCenter Server Domain Name oder IP address* ein. Wenn Sie einen Domänennamen eingeben, müssen Sie auch die IP-Adresse eines aktiven DNS-Servers in das angezeigte Feld *DNS Server IP Address* eingeben.
. Geben Sie die Anmeldeinformationen eines vSphere-Administrators in den Feldern *Benutzername und Passwort* ein.
. Wählen Sie *Weiter*.


[discrete]
== Weitere Informationen

* link:firmware_driver_versions.html["Unterstützte Firmware- und ESXi-Treiberversionen für NetApp HCI und Firmware-Versionen für NetApp HCI Storage Nodes"]

